# Generated by Django 3.1.7 on 2021-03-26 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result', models.CharField(choices=[('A', 'All'), ('V', 'Verbatim')], max_length=1)),
            ],
        ),
    ]
